### ISSUE TITLE
LAPIC and IOAPIC addresses on x86

### ISSUE THREAD

**Issue by zamaudio** [AlmuHS/GNUMach_SMP#11]
@AlmuHS: in coreboot, the LAPIC address is hardcoded to 0xfee00000 as it never changes on any x86 machine, so it's not really necessary to read it out of the ACPI.  Same for the IOAPIC address, it is always 0xfec00000.

**Comment by AlmuHS** [comment]
I have to read ACPI tables to find the processors (and their APIC ID), anyway. 
So, read the LAPIC common address don't add so much difficult.

The difficult was in reserve this address to assign a pointer, and this must be done even if I hardcode the address.
