### ISSUE TITLE
Improve testing using docker system

### ISSUE THREAD

**Issue by alonsomaniaco** [AlmuHS/GNUMach_SMP#12]
Hi all!

I have been checking a bit the project and I think docker would be a good tool to integrate here in order to aid the testing.
If we add the gnumatch.gz on boot folder on a docker image and instead of copying it on our own machine we can avoid the reboot process.

¿makes sense? 

note: Really good job here!

**Comment by AlmuHS** [comment]
It's a complex task. Hurd is not Linux: is a fully new kernel, with a very different behavior.
And, If I remember well, Docker usually shares the kernel with the host machine (like chroot).

Added to this, Qemu allows a remote debugging in hardware level, allowing to check the register values in back level, much deeper than Docker allows.

So, I'm not clear if Docker could be a correct solution. This is a too deep level for this.

**Comment by alonsomaniaco** [comment]
I'm not a very expert on this type of things. I think you are right, maybe docker is so high level if you need this type of debugging level so I think we can close this issue.

Thanks for all your work for opensource! :muscle:
